[env:c3-hwtest]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
  -DBOARD_VIEWE_UEDX24240013_MD50E
lib_deps =
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.3
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
  https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
