"""Embed the shared mobile UI; --check detects stale generated firmware assets."""
from pathlib import Path
import argparse
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
root=Path(__file__).resolve().parent.parent
out='#pragma once\n// Generated by scripts/embed_setup.py from web/setup.css and web/setup.js.\n'
for suffix in ('css','js'):
 text=(root/'web'/('setup.'+suffix)).read_text()
 assert ')SETUP"' not in text
 out+=f'inline const char setup_{suffix}[] PROGMEM=R"SETUP({text})SETUP";\n'
target=root/'include/mobile_setup_assets.h'
if args.check:
 assert target.read_text()==out,'Run python scripts/embed_setup.py'
else: target.write_text(out)
