#!/usr/bin/env python3
"""Regenerate the original's compact, worldwide scheduled large-airport pack.
OurAirports data is public domain: https://ourairports.com/data/
No downloads are needed to build firmware; the generated header is committed.
"""
import csv
import io
import json
import urllib.request
from datetime import date
from pathlib import Path

SOURCE = 'https://davidmegginson.github.io/ourairports-data/'

def rows(name):
    req = urllib.request.Request(SOURCE + name, headers={'User-Agent': 'EchoScope-airport-pack/1.0 (https://github.com/MrPsyware/echoscope)'})
    with urllib.request.urlopen(req, timeout=60) as r:
        return list(csv.DictReader(io.StringIO(r.read(32 * 1024 * 1024).decode('utf-8-sig'))))

def number(s):
    return format(float(s), '.7f') + 'f'

def main():
    airports = [a for a in rows('airports.csv') if a['type'] == 'large_airport' and a['scheduled_service'] == 'yes']
    runways = {}
    for r in rows('runways.csv'):
        if r['closed'] != '0' or not all(r[k] for k in ('le_latitude_deg','le_longitude_deg','he_latitude_deg','he_longitude_deg')):
            continue
        runways.setdefault(r['airport_ident'], []).append(r)
    lines = ['#pragma once', '// Generated by scripts/update_airports.py; OurAirports public-domain data.',
             f'// Retrieved {date.today().isoformat()}; worldwide large airports with scheduled service.',
             'namespace standalone {', 'inline constexpr Airport builtInAirports[]={']
    for a in sorted(airports, key=lambda a: a['ident']):
        code = a['iata_code'] or a['ident']
        name = a['name'].encode('ascii', 'replace').decode()[:63]
        rs = sorted(runways.get(a['ident'], []), key=lambda r: -float(r['length_ft'] or 0))[:3]
        packed = []
        for r in rs:
            packed.append('{' + json.dumps((r['le_ident'] + '/' + r['he_ident'])[:11]) + ',' + ','.join(number(r[k]) for k in ('le_latitude_deg','le_longitude_deg','he_latitude_deg','he_longitude_deg')) + '}')
        lines.append('{' + ','.join([json.dumps(code),json.dumps(a['ident']),json.dumps(name),number(a['latitude_deg']),number(a['longitude_deg']),str(len(rs)), '{'+','.join(packed)+'}']) + '},')
    lines += ['};', '}']
    Path('include/standalone_airports_data.h').write_text('\n'.join(lines)+'\n')
    print(f'Generated {len(airports)} airports')

if __name__ == '__main__':
    main()
